services:
  image_storage:
    build:
      context: .
    restart: always
    volumes:
      - ./app:/src/app
      - ./data:/data
    environment:
      CLIENTS_INFO__0__api_key: api_key
      CLIENTS_INFO__0__id: client
      STORAGE__TYPE: disk
      STORAGE__DISK__PATH: /data
      SENTRY__DSN: ${SENTRY_DSN}
    ports:
      - 5000:5000
