services:
  image_storage:
    build:
      context: .
      target: prod
    restart: always
    environment:
      UPLOAD_FOLDER: /uploads
      CLIENTS_INFO__0__api_key: api_key
      CLIENTS_INFO__0__id: client
    ports:
      - 5000:5000
    volumes:
      - ./uploads:/uploads
