  image_storage:
    build: https://github.com/Eldies/image_storage.git
    restart: always
    environment:
      UPLOAD_FOLDER: /uploads
      CLIENT_CREDENTIALS_1: client:api_key
    ports:
      - 5000:5000
    volumes:
      - ./uploads:/uploads
