services:
  image_storage:
    build:
      context: .
      target: prod
    restart: always
    environment:
      UPLOAD_FOLDER: /uploads
      CLIENT_CREDENTIALS_1: client:api_key
    ports:
      - 5000:5000
    volumes:
      - ./uploads:/uploads
