[tool.poetry]
name = "image_storage"
version = "0.1.0"
description = ""
authors = ["Dmitry Lavrukhin <dlavrukhin@yandex.ru>"]

[tool.poetry.dependencies]
python = "~3.10.0"
fastapi = "~0.111"
uvicorn = "~0.29"
base58 = "2.1.1"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "~8.2.0"
pytest-cov = "^5.0.0"
pytest-asyncio = "^0"
pyfakefs = "5.0.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
flake8 = "^5.0.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts ="""
    --capture=tee-sys
    -s
    -vv
    -p no:cacheprovider
    --strict-markers
"""
