image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []

ingress:
  enabled: false
  host: hostname

storage:
  s3:
    url: ""
    access_key: ""
    secret_key: ""
    bucket: ""

sentry:
  dsn: ""

clientsInfo: []
#  - id:
#    apiKey:
