apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-config
type: Opaque
stringData:
  SENTRY__DSN: {{ .Values.sentry.dsn }}
  STORAGE__TYPE: s3
  STORAGE__S3__URL: {{ .Values.storage.s3.url | quote }}
  STORAGE__S3__ACCESS_KEY: {{ .Values.storage.s3.access_key | quote }}
  STORAGE__S3__SECRET_KEY: {{ .Values.storage.s3.secret_key | quote }}
  STORAGE__S3__BUCKET: {{ .Values.storage.s3.bucket | quote }}

{{- if .Values.clients }}
{{- range $id, $client := .Values.clients }}
{{- $apiKey := required (printf "clients[%s].apiKey is required" $id) $client.apiKey }}
  CLIENTS__{{ $id }}__api_key: {{ $apiKey | quote }}
{{- end }}
{{- end }}
